### PR TITLE
Fix Image Cross Issue

### PR DESCRIPTION
**Pull request by Kumaravinash9**
<table>
<tr> 
<td>

<td>
<td>
 
</td>
<td>

</td>
<td>

</td>
</tr>
</table>
<h1>Group Chat</h1>

Screenshot 2021-08-16 at 11 27 00 PM
<h1>Distance Chat</h1>

Screenshot 2021-08-16 at 10 13 53 PM

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
@csoler  It has some fixes of message cross issues.

**Comment by Kumaravinash9** [comment]
@csoler  Please merge this PR.

**Comment by csoler** [comment]
May I merge this already?

**Comment by Kumaravinash9** [comment]
> May I merge this already?
 Okk Please merge this chnages.

**Comment by csoler** [comment]
Seems to work ok.

**Comment by Kumaravinash9** [comment]
> Seems to work ok.

please merge this PR.

**Pull request merged**
