### PR TITLE
Migrating the statemangement tool from redux to provider

### LINKED ISSUE #4: import  Account feature  is not implemented yet.
WhatsApp Image 2021-06-08 at 23 21 43

### LINKED ISSUE #7: we only able to create Pseudo identity and we are also not able to edit the idenitity

### LINKED ISSUE #11: QR code working

### LINKED ISSUE #12: Migrating Statemangement tool from Redux to Provider Package
Related Doc  : https://pub.dev/packages/provider

### LINKED ISSUE #15: Search screen bug
https://user-images.githubusercontent.com/64456168/123484050-5b5eb700-d625-11eb-86ea-d301f83a1457.mp4

### PR DESCRIPTION
**Pull request by Kumaravinash9**
Fix #12 
Fix #15 
Fix #4 
Fix #7
Fix #11 
Don't merge these changes. It's completed yet. Some screens have migrated  like :
 
* SignIn screen 
* Signup screen
* Friend Location
* add Friend 
* change Identity
* create Identity
* Home Screen (partially)
As well as I also refactor the codebase and also fix some bugs.

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
@csoler and @defnax

**Comment by Kumaravinash9** [comment]
Added two more screens  : 
* discover_ chat screen
*  search Screen

**Comment by defnax** [comment]
Hi, main goal of rs mobile easy and useable, i mean not overload the mobile ui stay easy like Whatsapp/Telegram

Search screen is for?

**Comment by Kumaravinash9** [comment]
@csoler, All screens has migrated with new statemangement tool.

**Comment by Kumaravinash9** [comment]
This PR is now ready to merge. Tomorrow i will remove the conflicts

**Comment by Kumaravinash9** [comment]
@csoler I am trying to pass this function for export the account but each time it is returning false means some error happens

## Func define:
```Future<bool> exportIdentity(String filePath, String pgpId) async {
  final response =
      await http.post('http://localhost:9092/rsAccounts/ExportIdentity',
          headers: {
            HttpHeaders.authorizationHeader:
                'Basic ' + base64.encode(utf8.encode('$authToken'))
          },
          body: json.encode({"filePath": filePath, "pgpId": pgpId}));
  print(response.body);
}
```
## Func Call : 
``` Directory appDocDir =await getApplicationDocumentsDirectory();
                                String appDocPath = appDocDir.path;
                                final id = Provider.of<AccountCredentials>(
                                        context,
                                        listen: false)
                                    .lastAccountUsed
                                    .pgpId;
                                await exportIdentity('$appDocPath', id);
```

**Comment by defnax** [comment]
maybe it has todo with this?
https://github.com/RetroShare/RetroShare/pull/2432

**Comment by Kumaravinash9** [comment]
Preview of QR code :

https://user-images.githubusercontent.com/64456168/124395952-a1520400-dd24-11eb-86cd-aa52bf245b12.mp4

**Comment by Kumaravinash9** [comment]
Now Working on issue : #6

**Pull request merged**
