### PR TITLE
Refactor codes and Renamed some variable names

### PR DESCRIPTION
**Pull request by Kumaravinash9**

### CODE REVIEW

**Comment by defnax** [comment]
can you make a new mobile apk please for testing? lets see if the create profile issue is gone

**Comment by defnax** [comment]
is ther some changes on that wrapper stuff? or you use a new wrapper code?
https://gitlab.com/Kumaravinash9/openapi-dart-retroshare-api-wrapper
image

**Comment by obrasero** [comment]
This code lost its compilability.
The "
@Kumaravinash9
Renamed some variable names "-Checkin missed to rename all needed.
Added a PR into your Repo.

**Comment by obrasero** [comment]
> lets see if the create profile issue is gone

Profiles with this code are still not creatable on my phone.
Also the phenomenology has changed.
I repoted this already anywhere.

**Comment by Kumaravinash9** [comment]
> This code lost its compilability.
> The "
> @Kumaravinash9
> Renamed some variable names "-Checkin missed to rename all needed.
> Added a PR into your Repo which fixes it,.

Actually i did that changes on my local device but forget to push. Thanks

**Comment by Kumaravinash9** [comment]
Image issue has solved 

Screenshot 2021-08-16 at 10 13 53 PM

**Comment by defnax** [comment]
But on rs qt desktop distant chat i can send normaly higher quality picture but now on rs mobile very short one.

when you click on the picture need a fullview option
image

picture limitation is only for chat rooms, distant chat picture attachment needs to be optimized allow higher dimensions

**Comment by Kumaravinash9** [comment]
Group chat issue has solved now

Screenshot 2021-08-16 at 11 27 00 PM

**Comment by Kumaravinash9** [comment]
@csoler  can you please merge this PR.

**Pull request merged**
