### PR TITLE
Added retroshare as a background service

### PR DESCRIPTION
**Pull request by Kumaravinash9**
Fix: #59 
Fix:  #58 
# Changes comitted
* Merge the current branch with the retroshare master.
* Now we donot need to install the retroshare service seperatly  in the mobile phone.
* Added permission Plugin and their functionality in QR screen.
* Refactor codes

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
this error is coming  

 ```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No 
implementation found for method share on channel plugins.flutter.io/share)
E/flutter ( 9056): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 9056): <asynchronous suspension>
E/flutter ( 9056):
```
I have already tried all the solution that is present on stackflow : [here](https://stackoverflow.com/questions/57163091/no-implementation-found-for-method-pickimage-on-channel-plugins-flutter-io-image)

**Comment by Kumaravinash9** [comment]
> this error is coming with those plugins which use method channel. Need help : @selankon @csoler
> 
> ```
> [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No 
> implementation found for method share on channel plugins.flutter.io/share)
> E/flutter ( 9056): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
> E/flutter ( 9056): <asynchronous suspension>
> E/flutter ( 9056):
> ```
> 
> I have already tried all the solution that is present on stackflow : [here](https://stackoverflow.com/questions/57163091/no-implementation-found-for-method-pickimage-on-channel-plugins-flutter-io-image)

Fixed Issue

**Comment by Kumaravinash9** [comment]
@csoler  please check this PR

**Comment by defnax** [comment]
image

**Comment by defnax** [comment]
but i get now worked with emulator
image

**Comment by Kumaravinash9** [comment]
> profile was successful but i wasnt able login, and create a new profile gets errors image image

Running a app in background cause background compatibility issue. That's why this error is coming. Background compability issue was solved yet.  I only added retroshare service inside the retroshare mobile. So that we donot have to install retroshare service separately.

**Comment by defnax** [comment]
starting distant chat from mobile not works properly, from qt to mobile works good.
image

no status if contact is online or chat is etablished with contact

**Comment by Kumaravinash9** [comment]
> starting distant chat from mobile not works properly, from qt to mobile works good. image
> 
> no status if contact is online or chat is etablished with contact

are you able to send images and emojis or able to change the profile pic

**Comment by Kumaravinash9** [comment]
> starting distant chat from mobile not works properly, from qt to mobile works good. image
> 
> no status if contact is online or chat is etablished with contact

something retroshare service takes buffer time to send message or receive message

**Comment by defnax** [comment]
- smileys are very small not sure maybe issue on emulator.
- some time the stickers/pictures from rs chat doesnt sended to rs mobile chat
- the picture quality is very bad (rs mobile to rs chat)

image

**Comment by defnax** [comment]
- when qt rs chat user closing the chat, normaly the tunnel is closed.
- you doesnt see if contact user is online or if the chat is active (tunnel etablished and green)
- restart a new chat from mobile still not works to rs chat, doesnt see any status whats going on, only seems one time i get the status( starting distant chat...)

**Comment by Kumaravinash9** [comment]
@cslor please review this PR

**Comment by csoler** [comment]
it looks like to added lots of cache and compilation files into the PR. This is most probably a mistake. Please remove them before we can merge.

**Comment by Kumaravinash9** [comment]
I have deleted all Unwanted files [build](https://github.com/RetroShare/retroshare-mobile/tree/master/android/app/build) from the repo.

**Pull request merged**
