### PR TITLE
typo in readme.md

### PR DESCRIPTION
**Pull request by altcoinpirate**

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
Thanks for PR @altcoinpirate.

**Comment by defnax** [comment]
@Kumaravinash9 where is the latest apk for testing? its importend to give feedback what works or not.

**Comment by Kumaravinash9** [comment]
@defnax  test it 
https://drive.google.com/file/d/1FHPVs7pqNuzG42vYbNIf_RfuJFFgrtb3/view?usp=sharing

**Comment by defnax** [comment]
the apk dont load i see always loading...

**Comment by defnax** [comment]
image

**Pull request merged**
