### PR TITLE
added shimmer effect and added some APIs

### PR DESCRIPTION
**Pull request by Kumaravinash9**
Fix: 
 #24 
#36
 #37 

<table>
<tr>
<th>

</th>
<th>

</th>
</tr>
</table>

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
https://drive.google.com/file/d/1_3LTBwK_PDZDksTIf5gBAio5CNWmpWma/view?usp=sharing
@defanx and @obrasero @csoler   can you please test it. Is it working or not.

**Comment by obrasero** [comment]
OK, i downloaded it.
Now i go to sleep.
tomorrow i will test.

As the main-problem until now in my testings is the frequently and quick service-down this will than be the test i can provide.
Is the checkin "handling-down" restarting the service?
Also i think, the reason why the service frequently shuts down if the rs-mobile is started should be determined.

**Comment by defnax** [comment]
doesnt not works like your screenshot, but im using bluestacks emulator. i see few milliseconds something not more

**Comment by Kumaravinash9** [comment]
> doesnt not works like your screenshot, but im using bluestacks emulator. i see few milliseconds something not more

I am asking are you able to login or not. And Please check the friend identity as well as

**Comment by defnax** [comment]
> > doesnt not works like your screenshot, but im using bluestacks emulator. i see few milliseconds something not more
> 
> I am asking are you able to login or not. And Please check the friend identity as well as

login works but slow, im waiting 1-2 minutes

**Comment by Kumaravinash9** [comment]
> > > doesnt not works like your screenshot, but im using bluestacks emulator. i see few milliseconds something not more
> > 
> > 
> > I am asking are you able to login or not. And Please check the friend identity as well as
> 
> login works but slow, im waiting 1-2 minutes

Create profile

**Comment by defnax** [comment]
image

but i must do via mouse click to get that effect it doesnt stays long , on friends locations doesnt works
image

**Comment by Kumaravinash9** [comment]
> image
> 
> but i must do via mouse click to get that effect it doesnt stays long , on friends locations doesnt works
> image

In Friend_location, It should work

**Comment by defnax** [comment]
create profile stays endless like same before, but this after closing rs mobile and restart the new profile is not generated
image

**Comment by Kumaravinash9** [comment]
> create profile stays endless like same before, but this after closing rs mobile and restart the new profile is not generated
> image
> 
> i come till create identity

Actually it will work. Intially it take some time. I have tested it

**Comment by Kumaravinash9** [comment]
> create profile stays endless like same before, but this after closing rs mobile and restart the new profile is not generated
> image
> 
> i come till create identity

Actually it will work. Intially it take some time. I have tested it

**Comment by defnax** [comment]
i get now work distant chat, but you never know if the chat tunnel etablished in the distant chats with contacts.

**Comment by defnax** [comment]
i found a issue when leaving the distant chat on rs mobile the tunnels seems stays active,
i see online the chat on my rs desktop

**Comment by Kumaravinash9** [comment]
@csoler  did you check this App

**Comment by defnax** [comment]
it will come a working version with profile generation? not easy to test the rs-mobile with profile generation issues

**Comment by Kumaravinash9** [comment]
WhatsApp Image 2021-08-09 at 22 21 13

**Comment by defnax** [comment]
this word is to big use short text as possible
image

**Comment by defnax** [comment]
Hi i has now succes more with apk, attempting to test via the emulator

but gets issues where get the package or how to install



> C:\Users\ProBook\Documents\GitHub\retroshare-mobile>flutter run
> No supported devices connected.
> The following devices were found, but are not supported by this project:
> Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
> Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.70
> If you would like your app to run on web, consider running `flutter create .` to generate projects for these platforms.
> 
> 
> C:\Users\ProBook\Documents\GitHub\retroshare-mobile>flutter devices
> 3 connected devices:
> 
> ONEPLUS A5000 (mobile) • emulator-5554 • android-x86    • Android 7.1.1 (API 25)
> Chrome (web)           • chrome        • web-javascript • Google Chrome 92.0.4515.131
> Edge (web)             • edge          • web-javascript • Microsoft Edge 91.0.864.70
> 
> C:\Users\ProBook\Documents\GitHub\retroshare-mobile>flutter run
> Because retroshare depends on openapi from path which doesn't exist (could not find package openapi at "..\openapi-dart-retroshare-api-wrapper"), version solving failed.
> Running "flutter pub get" in retroshare-mobile...
> pub get failed (66; Because retroshare depends on openapi from path which doesn't exist (could not find package openapi
> at "..\openapi-dart-retroshare-api-wrapper"), version solving failed.)
> 
> C:\Users\ProBook\Documents\GitHub\retroshare-mobile>

**Comment by defnax** [comment]
found the packages, but running from flutter console is slow?
image

**Comment by defnax** [comment]
ok i found on android studio i need create virtual device but i started via chrome the rs-mobile
from console get no sucess to find a emultor device
image

**Comment by obrasero** [comment]
Yes,
you can
>  run from android studio directly retroshare-mobile?

In Menu "run"
select "run" for release building with run
or debug for debug building with run.

The first call is "slow" as the srces must all get build.
Follow-up calls to run or debug - if you dont change in code- will be quicker.
But nevertheless if you call debug its will be also slower running caused by the debug-instrumentation included.

But.
if you only want repeatadly start the rs-mobile without interest in the debug-output or breakpoint setting you also can just start the installed apk-s without flutter or android.
The traces are anyway avail.

**Comment by obrasero** [comment]
> i found on android studio i need create virtual device ... get no sucess to find a emultor device image

Did you follow my description to setup the android/-studio/flutter?
The steps worked to me. i tested them an 2 different laptops.

At which step got it "out-of-order"
Maybe i must adapt the description to be clearer or better?

**Comment by defnax** [comment]
> > @defnax
> > i found on android studio i need create virtual device ... get no sucess to find a emultor device image
> 
> Did you follow my description to setup the android/-studio/flutter?
> The steps worked to me. i tested them an 2 different laptops.
> 
> At which step got it "out-of-order"
> Maybe i must adapt the description to be clearer or better?

you has removed the howto PR, without it was merged

**Comment by Kumaravinash9** [comment]
> > > @defnax
> > > i found on android studio i need create virtual device ... get no sucess to find a emultor device image
> > 
> > 
> > Did you follow my description to setup the android/-studio/flutter?
> > The steps worked to me. i tested them an 2 different laptops.
> > At which step got it "out-of-order"
> > Maybe i must adapt the description to be clearer or better?
> 
> you has removed the howto PR, without it was merged

I can help  you with android studio

**Comment by obrasero** [comment]
> 
> 
> > > @defnax
> > > i found on android studio i need create virtual device ... get no sucess to find a emultor device image
> > 
> > 
> > Did you follow my description to setup the android/-studio/flutter?
> > The steps worked to me. i tested them an 2 different laptops.
> > At which step got it "out-of-order"
> > Maybe i must adapt the description to be clearer or better?
> 
> you has removed the howto PR, without it was merged

Ouhh...
that was not intended.
Seems than a side effect of my the checkin from my local repo-clone.
I try to correct it..., meaning the unintended close of the push rew to reopen.....
one  moment.

**Comment by defnax** [comment]
> In Menu "run"
> select "run" for release building with run
> or debug for debug building with run.

image
yes used the release run 
 
> if you only want repeatadly start the rs-mobile without interest in the debug-output or breakpoint setting you also can just > > start the installed apk-s without flutter or android.
where is the installed apk's? on Android studio?

> The traces are anyway avail.
> 
> I myself only test with usb-plugged in physical device.

i need buy next month a testing android phone for rs mobile.

**Comment by Kumaravinash9** [comment]
Ypu can use emulator then you donot have to download the mobile.

**Comment by defnax** [comment]
> Ypu can use emulator then you donot have to buy the mobile.



> Ypu can use emulator then you donot have to buy the mobile.

without a real phone cant test how is it useable then on a notebook emulator, it different via phone

**Comment by obrasero** [comment]
OK. howto hopefully back again.

**Comment by defnax** [comment]
hope a useable apk will be published with a fix the profile creation issue, i only tested the other ways how to run rs-mobile from flutter or android studio useful for new android devs.
Lets see next days and weeks.

**Comment by Kumaravinash9** [comment]
> hope a useable apk will be published with a fix the profile creation issue, i only tested the other ways how to run rs-mobile from flutter or android studio useful for new android devs.
> Lets see next days and weeks.

THIS WILL FIX SOON. I AM CURRENTLY WORKING ON IT. ON WEDNESDAY IT WILL FIX NOW.

**Comment by obrasero** [comment]
Emulator, by the way is to slow to me on my laptops :).
> hope a useable apk will be published with a fix the profile creation issue

The problems i showed with the trace files in my tests do not only happen on profile creation. They happen all service actions round.
If i was lucky to get successful behind profile generation i got the same game at for exc. identity creation.

As Service unsinstall and reinstall removes the old profile data, and i tested with different service versions i actually completly stick in profile creation.
So this is just the first border to take. 
I press all thumbs to @Kumaravinash9  - dont know thje correct english phrase for it - ;)

**Comment by defnax** [comment]
> As Service unsinstall and reinstall removes the old profile data, and i tested with different service versions i actually completly stick in profile creation.
> So this is just the first border to take.

me too no sucess more and updating/reinstalling service you losing your profile, at the moment its bad to update your service all is lost.

**Comment by obrasero** [comment]
A question comes into mind @Kumaravinash9 .
i looked through the code and it seems to me that in profile creation the code should catch the exceptions and at least come out with the error-dialog that the service may be down.
But in my tests none of the both exceptions allways got catched and showed this problem hint.
The just allways ended in an endless working profile-generation.

What is the reason for this?

**Comment by Kumaravinash9** [comment]
> A question comes into mind @Kumaravinash9 .
> i looked through the code and it seems to me that in profile creation the code should catch the exceptions and at least come out with the error-dialog that the service may be down.
> But in my tests none of the both exceptions allways got catched and so never showed this problem hint.
> They just always ended in an endless working profile-generation.
> 
> What is the reason for this?

Because retroshare service doesnot give the response of your request that why it moving forever.

**Comment by obrasero** [comment]
Yes, but it results into an exception, and to me your code looks like a catch-all.
That's what i don't understand.
Also i i debug the code line for line it just jumps with the exception out of the method completely ignoring both of your exception catch block the typed one as well as the catch(e) (catch all?)-version.

**Comment by obrasero** [comment]
To be more clear, -i'm talking about signup_screen the try gets catched with:
        try{....
        } on HttpException catch (err) {
      var errorMessage = 'Authentication failed';
      errorShowDialog(
          "Auth Failed", 'Something went wrong', context);
    } catch (e) {
      errorShowDialog('Retroshare Service Down',
          'Please ensure retroshare service is not down!', context);

    }

The try comes back with a socket or an incomplete header exception.
but stepping through the debugger shows that these exceptions get noct catched by at least the 2. catch, the cacth(e).

**Comment by defnax** [comment]
> To be more clear, -i'm talking about signup_screen the try gets catched with:
> 
> ` try{.... } on HttpException catch (err) { var errorMessage = 'Authentication failed'; errorShowDialog( "Auth Failed", 'Something went wrong', context); } catch (e) { errorShowDialog('Retroshare Service Down', 'Please ensure retroshare service is not down!', context);`
> }
> 
> The try comes back with a socket or an incomplete header exception.
> but stepping through the debugger shows that these exceptions get noct catched by at least the 2. catch, the cacth(e).

maybe you can try the old rs mobile from b1rd if it has the same issue? with profile creation?
i never hear from @b1rd that there are profile creation issues.
or its a new bug from this year
https://gitlab.com/b1rdG/retroshare-android-flutter-app

**Comment by obrasero** [comment]
I'm not searching with this a way around the creation bug.
I'm searching to understand the code, especially the working of the flutter exception in this case.
So a code-understanding question.
Or what do i understand wrong in the flutter-exception-catch code semantic above, as it obviously does not do what i would await if i see such a code.

**Comment by Kumaravinash9** [comment]
> To be more clear, -i'm talking about signup_screen the try gets catched with:
> 
> try{....    
>     } on HttpException catch (err) {  
>       var errorMessage = 'Authentication failed';  
>       errorShowDialog(  
>           "Auth Failed", 'Something went wrong', context);  
>     } catch (e) {  
>       errorShowDialog('Retroshare Service Down',  
>           'Please ensure retroshare service is not down!', context);  
>     }
> The try comes back with a socket or an incomplete header exception.
> but stepping through the debugger shows that these exceptions get noct catched by at least the 2. catch, the cacth(e).

Showing exception  to user  that makes no sense that'why I didn't return the err there

**Comment by Kumaravinash9** [comment]
> > To be more clear, -i'm talking about signup_screen the try gets catched with:
> > ` try{.... } on HttpException catch (err) { var errorMessage = 'Authentication failed'; errorShowDialog( "Auth Failed", 'Something went wrong', context); } catch (e) { errorShowDialog('Retroshare Service Down', 'Please ensure retroshare service is not down!', context);`
> > }
> > The try comes back with a socket or an incomplete header exception.
> > but stepping through the debugger shows that these exceptions get noct catched by at least the 2. catch, the cacth(e).
> 
> maybe you can try the old rs mobile from b1rd if it has the same issue? with profile creation?
> i never hear from @b1rdG that there are profile creation issues.
> or its a new bug from this year
> https://gitlab.com/b1rdG/retroshare-android-flutter-app

This code have some bug and will not work properly with new retroshare service because some retroshare api has been discarded now.

**Comment by obrasero** [comment]
> 
> 
> > To be more clear, -i'm talking about signup_screen the try gets catched with:
> > try{....
> > } on HttpException catch (err) {
> > var errorMessage = 'Authentication failed';
> > errorShowDialog(
> > "Auth Failed", 'Something went wrong', context);
> > } catch (e) {
> > errorShowDialog('Retroshare Service Down',
> > 'Please ensure retroshare service is not down!', context);
> > }
> > The try comes back with a socket or an incomplete header exception.
> > but stepping through the debugger shows that these exceptions get noct catched by at least the 2. catch, the cacth(e).
> 
> Showing exception to user that makes no sense that'why I didn't return the err there

Sorry for anoying you, yes my english is not good.
I will try again.
1. my question is about flutter-code not about errors in your code or questions if returning an error makes or makes no sense.

I see in your code the cited sequence try{...}..catch(e){...}
And in try an exception happens but the catch-part does not catch this exception and instead leaving it unhandled through.
I try to understand flutter-semantic in exception handling and wonder why the exception gets not catched at least by your catch(e), which than should result as i understand this code in an errorShowDialog('Retroshare Service Down'..).
This error-dialog does not pop up and debugging also shows, that the exception just gets not catched by the given catch-block.
I wonder why it is not catched, where is my missunderstanding of the flutter try-catch in this code?

**Comment by Kumaravinash9** [comment]
Actually we are not  catching the exception  where we are doing http request for signup. 
https://github.com/RetroShare/retroshare-mobile/blob/de02052facc01fdbb27444ab310669472c562966/lib/services/account.dart#L84

**Comment by Kumaravinash9** [comment]
Socket exception comes only when your service will not accept the request. Means retroshare service deny the http request

**Comment by obrasero** [comment]
Ouhh i see, my english is realy a problem.

Your code above:
<pre>try{...}
on HttpException catch (err){do1}
catch(e){do2}</pre>
- - -
I interpret it as:
if an http-exception comes up in try{...}
catch it and process do1.
if any other type of exception comes up in try...
catch it and process do2.
- - -
Any misinterpretation in it?
- - - - -
Now in fact in try i see in my tests come 2 exceptions up:
e1)Sometimes a the socket-exception, 
e2) actual mostly the "Connection closed before full header was received" exception.

Now if for exc. e2 is a Http-exception it should get catched by onHttp.. and "do1" should get processed.
If it is not an http-exception than - following my interpretation above - 
it should get catched(e) and "do2" should get processed.
Fact is: none of both get processed in e2-case, the e2 just gets not catched.

So what is wrong with my above interpretation, why can the exception go out without beeing catched?

**Comment by obrasero** [comment]
Ahhh.. in  now looked in a dart-artikle about dart exception and think i got it:
The signup in your try-code is an async method which is called in your code without the "await"-keyword.
Thats why the exception catch has no effect on exceptions coming while processing singup.

==> i will try adn testwise add an await to see if then do2 gets processed on the "closed before full header" exception....

**Comment by obrasero** [comment]
OK. tested it but instead of using await by not waiting and instead using error-callback
like i checked in:

**Comment by Kumaravinash9** [comment]
> OK. tested it but instead of using await by not waiting and instead using error-callback
> like i checked in:

Await is used whatever place is needed. Can you please point me out where is not added

**Comment by Kumaravinash9** [comment]
> OK. tested it but instead of using await by not waiting and instead using error-callback
> like i checked in:

Await is used whatever place is needed. Can you please point me out where is not added

**Comment by obrasero** [comment]
I showed it already to you in my code citations.
There is onyl one place in your signup_screen.dart code where an on HttpException catch is done.
But my checkin above should also show the codeplace i was talking about in my dart-learning questions to you.

**Comment by obrasero** [comment]
Ahh.. maybe you think i'm using the rs/rs-mobile code.
I'm using your masterbranch avins/rs-mobile.

With the checkin 
e6865e704134aa19df3011f6e085597290e299db
"Handling retroshare service down"
you introduced exception catching over the call of 
account_signup.signup(.....)
in createAccount.

but the catch never worked in my cases and as i now understand caused by the missing "await"

**Comment by Kumaravinash9** [comment]
@csoler  please merge this PR.

**Comment by obrasero** [comment]
Only a question:
What about to handle the 2 packages dart-see and api-wrapper 
as git-submoduls within the rs-mobile?
This could ensure that there repos and repo locations are consistent by git-update.
Actual i added the info where to find the repos and how to name the folder of the local clones into the howto ( #35 )

**Comment by obrasero** [comment]
I'm trying to run your new master.
it breaks on my phone in
auth.dart at 37
<pre>e = {_TypeError} type '_Exception' is not a subtype of type 'String'
 _stackTrace = {_StackTrace} 
 _url = "package:retroshare/provider/auth.dart"
 _line = 51
 _column = 27
 _message = "type '_Exception' is not a subtype of type 'String'"</pre>

**Comment by Kumaravinash9** [comment]
> I'm trying to run your new master.
> it breaks on my phone in
> auth.dart
> 
> e = {_TypeError} type '_Exception' is not a subtype of type 'String'
>  _stackTrace = {_StackTrace} 
>  _url = "package:retroshare/provider/auth.dart"
>  _line = 51
>  _column = 27
>  _message = "type '_Exception' is not a subtype of type 'String'"
> With the result rs-mobile hangs in "get locations" after start.

@obrasero  Fixed Now. And Thanks

**Comment by Kumaravinash9** [comment]
> I'm trying to run your new master.
> it breaks on my phone in
> auth.dart
> 
> e = {_TypeError} type '_Exception' is not a subtype of type 'String'
>  _stackTrace = {_StackTrace} 
>  _url = "package:retroshare/provider/auth.dart"
>  _line = 51
>  _column = 27
>  _message = "type '_Exception' is not a subtype of type 'String'"
> With the result rs-mobile hangs in "get locations" after start.

Dart SEE :
https://gitlab.com/Kumaravinash9/retroshare-dart-see
Retroshare_wrapper : 
https://github.com/Kumaravinash9/Retroshare-Wrapper.git

**Comment by obrasero** [comment]
Yes @Kumaravinash9 , i know.
Did already adapt the #35 

But what about my question to manage these packages as git-submodules in rs-mobile?
Benefit: just cloning rs-mobile would ensure that the packages are taken form the correct repo(repo-state) and an extra docu where they are would not be needed as well to adapt the local folder-names of theses packages would be managed by the rs-mobile repo.

**Comment by Kumaravinash9** [comment]
I will do that @obrasero. Once I will complete it. I will add that feature into this.

**Comment by obrasero** [comment]
> 
> 
> I will do that @obrasero. Once I will complete it retro share the problem. I will add that feature to this.

If you want. i can try to do it for a as a learning task in flutter/dart.

**Comment by obrasero** [comment]
> 
> 
> > I'm trying to run your new master.
> > it breaks on my phone in
> > auth.dart
> > e = {_TypeError} type '_Exception' is not a subtype of type 'String'
> > _stackTrace = {_StackTrace}
> > _url = "package:retroshare/provider/auth.dart"
> > _line = 51
> > _column = 27
> > _message = "type '_Exception' is not a subtype of type 'String'"
> > With the result rs-mobile hangs in "get locations" after start.
> 
> @obrasero Fixed Now. And Thanks

Was not fixed. 
You fixed additional places og it :)

Checked in the fix now with
https://github.com/obrasero/retroshare-mobile/commit/89044a5ff646441f9bb94c255952d5ea093f48bb

you may pick it into your repo.

**Comment by obrasero** [comment]
Rechecked to run the code with theses fixes:

Exception: HttpException: Exception: something went wrong!
in: auth.dart; fetchAuthAccountList

**Comment by Kumaravinash9** [comment]
> Rechecked to run the code with theses fixes:

did you fetch my changes in your local

**Comment by Kumaravinash9** [comment]
> Rechecked to run the code with theses fixes:
> 
> OK now: error string issue
> 
> which no is able to show the real exception as:
> 
> Exception: HttpException: Exception: something went wrong!
> in: auth.dart; fetchAuthAccountList
> context: SplashScreen(dependencies: [MediaQuery], state: _SplashState#a3156)
> 
> ==> hanging with "Get locations"

please send me error log on retroshare desktop. Let's discuss on it

**Comment by obrasero** [comment]
Yes;
i allways take over your master to test into my repro:
If you wnat you may just ceck in my repo.
Its the dev/master-branch there.

And yes i also took over your api-wrapper and adapted the lokal path name. thats why i hinted to manage it as submodul in git.

**Comment by obrasero** [comment]
> please send me error log on retroshare desktop

retroshare desktop?
Not understand what you mean. is this a chatgroup in rs?

**Comment by obrasero** [comment]
@Kumaravinash9 
Found out how to make pull requests to your master ;)
So i added 3 as "All good things come in threes." ;)

**Comment by defnax** [comment]
> > please send me error log on retroshare desktop
> 
> retroshare desktop?
i think he mean direct chat on retroshare

**Comment by defnax** [comment]
New apk? The create profile issue is fixed ?

**Pull request merged**
