### PR TITLE
added Image support in Chat 

### PR DESCRIPTION
**Pull request by Kumaravinash9**
Related Link : 

1 . https://stackoverflow.com/questions/8571501/how-to-check-whether-a-string-is-base64-encoded-or-not
2. https://pub.dev/packages/flutter_html/example

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
Here is the drive link in which I uploaded the apk : https://drive.google.com/file/d/1_3LTBwK_PDZDksTIf5gBAio5CNWmpWma/view?usp=sharing

And please let me know if any functionality is not working.

**Comment by defnax** [comment]
Hi i has no Android Phone but i want test on bluestacks, its not best method, need to buy for rs a own android phone :)

**Comment by defnax** [comment]
tested on bluestack image attachment doesnt worked, maybe issue on bluestacks...
but i tested only on a empty chatroom .

But i find a isssue on profile creation, when generating you forget to add node name? when you forget every friend has noname? normaly we taked on qt ui, use the same name node name and identity name... when it only available in advanced then every rs mobile user gets no name?

cc retroshare retroshare_Screenshot_2021 07 27_20 10 31

**Comment by defnax** [comment]
i doesnt had success to connect with my RetroShare client. First wasnt able to add the key or short id.
image

**Comment by Kumaravinash9** [comment]
> tested on bluestack image attachment doesnt worked, maybe issue on bluestacks...
> but i tested only on a empty chatroom .
> 
> issues (tested on bluestacks):
> 
> 1. Add Friend via Retroshare id or cert gets errors
> 2. Attach image not worked
> 3. No notify when some one want or added you as friend
> 4. Import account not functional
> 5. Edit Profile seems not available? to change name or picture later
> 
> cc retroshare retroshare_Screenshot_2021 07 27_20 10 31

Short invite is not working as well as update Identity feature there is some problem with this apis. I already inform this to cyril.
Link : https://gitlab.com/elRepo.io/retroshare-wrapper-dart/-/issues/1

**Comment by Kumaravinash9** [comment]
But we can use retroshare long invite. It's working. I have tested it. and talking about image i have tested it yesterday it was working but i tested it on emulator, Will test it on real device

**Comment by defnax** [comment]
> But we can use retroshare long invite. It's working. I have tested it. and talking about image i have tested it yesterday it was working but i tested it on emulator, Will test it on real device

Long invite i get same error output, yes needs to be tested on a mobile device

**Comment by Kumaravinash9** [comment]
CQEGAcOVxsFNBGDokFUBEADuS7cXUdPzKl2kbCa8/3jwJnWGQTTBzHEhQwn7UE4gq7tQ5GYQ52cf8CMr81X8Qhk3dGou4Kx3WNNRyDhyBXwgQnZmmaPZbgc3PJAEIDhXtpE6GB7rT9/IldwhSonsF+oWE2fVEIFmg/K109lQXHFbFhABmCudYzIc4a1UxSws3sI8LpBzei61FTW8wrn2fSLHtJNqmhbGe82z8eMuqGrxS9f0sCP/oTRQMNbPsfu7aTUjFtjFtdX9j3qemdCksJmyCuaROlzT48zwQ/vp8g2nOxE1+bz/8io7eYMTcPZTIZe6qQ+P2s+aJ4sbu2IzgieSi8/kWxKSZLEHy2aPZqhVIKfJeXXxqGj/3Epq+Cdao4wkCAxuqW2Q1647h1g/aOxS6Dzzyfq7QWMCaaZS4DEIec5u6BUeuMP6fgghHCKgz+Xf5aUhgVyHuonlVn92BOnKdNEm66gta2C5x3LgMHPXUUiFycMyZDjfXn/rUwo0C85mlG+G+6DBInOgUsfMhsy+r8NUwytqFLXVKlWKhnYYPqqgXEQ4DCJT5BlMvKdQqv8nH3LNDCg+LlleyYcaA47DbELZk7V6Y5t/9zL2cgPee4s3YuY9MWwo+U0mz8/hjOR7WuCMJtU05AYMgpPZyR5092FTLkguITexUojb5LdSdxMApN+ArF5t40VtibEZnQARAQABzSFBdmluIChHZW5lcmF0ZWQgYnkgUmV0cm9TaGFyZSkgPD7CwV8EEwECABMFAmDokFUJEBdo1Fe+wLW6AhkBAABZOQ//Z77IwoNDhIIdyEqb2Ayu9mKYcVHQdfeb4WXW7OShN0QEeQS3FSKM6jwg+2IEYs4+qleyuzT8iErZaw34A5HGdkawCcV4ePhJxMR2PV/BrKQSTieMTSXhtqWoLciCJca+t0mDahfIyQPe+in92LyngQQdqB81+Rivq2PfPLVkRleBOzO01gFvHR0xcCWyr2cVWr8Pdmwkt84AHO+HccR/0eq8VrdrZ8aAMgRqVEov+HE9gwFZzxoJ4DcTtEmoJsc2BINHjhKk59yqUfmPErARWx2H/w7ZLh8wkTrttCQNFuhPRPlmZDLaxmSfqQEmlW6bliccqQbbY6cxh+mPUuDwe2relhK6UPQD4T/d+syq/+kkh6l0wIwhqRd6bY6PD29HUCOj9Rt2ckBm7ar7md/gYWZuTIEkYhY2yCjb+TCA9R3SdUrnnOnPPddoBjkqoNgNLMJyM5ciUsgbJ7+yjRG5ehZcj6sFCiDqb82SjpuXxR2Fmk9HrP6/M4i00TlKD4urfodD0yWlUxskkLhx+aqDRG4bCVqC2XBvVXAqnuV/NfwT2GNLtPwgL82+nxrKduLq1jy6Bf7i6PzRVe14tbDHPjEPI8/TV/edNeB7o1mSfegHcQkPjVpfTZvXqA2XoUUr2mRAHk7C+baXV8pX1QxzC8pF+AOyn0LKd9y7VYt+xv4CBnXWPL8mLwMGCgACECYvBAAGBk1vYmlsZQUQGmBvnaMBf7SUYR+IGUyA8AoVaXB2NDovLzEwLjAuMi4xNTo5Nzc1ChVpcHY0Oi8vMTAuMC4yLjE2Ojk3NzUKGmlwdjQ6Ly8xMTcuMjExLjYxLjIyNDo5Nzc1ChppcHY0Oi8vMTE3LjIxNC41Ny4xMzA6OTc3NQoaaXB2NDovLzExNy4yMTQuNjAuMTA0Ojk3NzUKGmlwdjQ6Ly8xMTcuMjE0LjYwLjE5MTo5Nzc1ChlpcHY0Oi8vMTE3LjIxNC42MC41OTo5Nzc1ChlpcHY0Oi8vMTE3LjIxNC42MS44Nzo5Nzc1ChtpcHY0Oi8vMTE3LjI1MS4yMTMuMjA1Ojk3NzUKG2lwdjQ6Ly8xMTcuMjUxLjIxNS4xMjc6OTc3NQcDqkNs

**Comment by Kumaravinash9** [comment]
try to add it

**Comment by Kumaravinash9** [comment]
Long invite is working

**Comment by defnax** [comment]
not easy to test, on bluestacks i have issues to login with the service apk
image
need to test next days

**Comment by Kumaravinash9** [comment]
Screenshot_1627414701

**Comment by Kumaravinash9** [comment]
On emulator it is working good but in phone share image is not working.i will fix this issue soon

**Comment by Kumaravinash9** [comment]
@csoler  did you test it

**Comment by defnax** [comment]
animated gif images would be cool too
https://pub.dev/packages/flutter_gifimage

**Comment by csoler** [comment]
I dont manage to test the app because it cannot create a profile. Which retroshare-service are you using? I suppose I need to install the right retroshare-service on my phone.

**Comment by defnax** [comment]
but he uses very old service from b1ird, we need normaly a new service apk

this wotrks on my bluestacks:
https://gitlab.com/Kumaravinash9/retroshare-android-apks/-/blob/master/retroshare-service-20200529.apk

**Comment by defnax** [comment]
@Kumaravinash9 which emulator you use?
for me it looks like there is issues to get logged in, profile generation works but it doesnt not continoue after creation or login, on bluestacks its fast but i get endless login trying. 
last night i had success to login 1-2 times

**Comment by defnax** [comment]
im not sure but i tested on two emulators. bluestacks and on memu.
Not sure if this is issue is still present on a real phone too

1. Profile generation works till the animation comes and it does not continoue.
2. After closing retroshare mobile and reopen the profile is available to login but then same issue it stays on attempt to login...

image


image

image

**Comment by defnax** [comment]
maybe cyril has the same issue like me

**Comment by defnax** [comment]
i found one issue when copy from rs qt a key the key looks not good then it doesnt adds it to the mobile

**Comment by defnax** [comment]
seems get connected but under friends no friends visible
image

image

**Comment by defnax** [comment]
now seems login works but it takes very long..
but private chat seems not done yet
on mobile i doesnt get yet any chat message 

image

**Comment by defnax** [comment]
ok sending from retroshare desktop to mobile it works images but seems only chat rooms working right?
image

But chat rooms has image limit not sure how to shrink or check image size for rs mobile
on private and distant chat we has no limiting

**Comment by defnax** [comment]
ok i see now friends but it taked very long to see it maybe slow on emulator.
But sending private message not working.
image
image

**Comment by Kumaravinash9** [comment]
> ok i see now friends but it taked very long to see it maybe slow on emulator.
> But sending private message not working.
> image
> image

Working on it.

**Comment by Kumaravinash9** [comment]
Will update you when i am done

**Comment by Kumaravinash9** [comment]
I donot think login takes long time. I have tested it two or more times and i worked properly

**Comment by Kumaravinash9** [comment]
As you can see when i reduce the size of the image it started working properly

**Comment by defnax** [comment]
Normaly share orginal image will maybe work for direct chat or distant chat ( there is no limit)
But i has two times myself in the Friends list

> I donot think login takes long time. I have tested it two or more times and it worked properly. The reason we are not able share the image because of the large image size.

**Comment by Kumaravinash9** [comment]
> Normaly share orginal image will maybe work for direct chat or distant chat ( there is no limit)
> But i has two times myself in the Friends list
> 
> > I donot think login takes long time. I have tested it two or more times and it worked properly. The reason we are not able share the image because of the large image size.

Talking about private chat is not implemented yet. For now, we can do only distance chat and group chat. And one more thing you will not notify when you are connected with new friend that's also not implemented. You will be notify only when you receive new chat.

**Comment by Kumaravinash9** [comment]
> Normaly share orginal image will maybe work for direct chat or distant chat ( there is no limit)
> But i has two times myself in the Friends list
> 
> > I donot think login takes long time. I have tested it two or more times and it worked properly. The reason we are not able share the image because of the large image size.

For that I will planning to add image compression inside the app. so it will reduced the size of image

**Comment by Kumaravinash9** [comment]
> Normaly share orginal image will maybe work for direct chat or distant chat ( there is no limit)
> But i has two times myself in the Friends list
> 
> > I donot think login takes long time. I have tested it two or more times and it worked properly. The reason we are not able share the image because of the large image size.

Talking about login. It worked properly from my side. I think it's the problem with the retroshare service

**Comment by defnax** [comment]
> Talking about private chat is not implemented yet. For now, we can do only distance chat and group chat. And one more thing you will not notify when you are connected with new friend that's also not implemented. You will be notify only when you receive new chat.

you will implement private chat?
Would be cool if we see Private, Distant Chats, Rooms all like in the Chats List, at the moment i see on only rooms there.
Like how in Telegram.

**Comment by defnax** [comment]
ok now i understand the Friends View is not for Private Chat...
i hoped private chat will work too.
Start distant chat will work from desktop to rs mobile, desktop user needs to start the chat to get a chat
image

on mobile no info if there is a attempt to start a distant chat
image

**Comment by defnax** [comment]
other bad issue you newer know if the contact is online or available to chat, else you can wait lots of to chat, when its not a direct friend, on direct friend you know if he is connected you can send him a chat message he can reply maybe later.
For me Direct Chat is importend till the Distant Chat is useable anytime later when it has all the importend features and stable.

**Comment by Kumaravinash9** [comment]
https://drive.google.com/file/d/1_3LTBwK_PDZDksTIf5gBAio5CNWmpWma/view?usp=sharing

**Comment by defnax** [comment]
Hi its working now , you has limited for rooms the image size?
image

**Comment by defnax** [comment]
look the image doesnt displayed on desktop
not sure if mobile to mobile will be displayed right?
image

**Comment by defnax** [comment]
Distant Chat does not work on rs mobile, or temporary, rs mobile to rs desktop nothing happens.
i need start from retroshare a distant chat to get a connection to the mobile identity.
but often it works only one way desktop to mobile.

Was great if we can chat direct too, before the issues are fixed with distant

**Comment by obrasero** [comment]
Hello,
i*ve tried to install the apk-s linked in this thread to try testing the rs-mobile-app:
Installed service apk and the mobile apk.
Started servive and than the rs-mobile:OK
On trying to create a profile, the creation process was never ending,
so the test stop before we could try to connect to mobiles via rs-mobile.

So what was wrong otr is there some specifics actual to be aware of to be able to create a profile?

I've an RS-TOR-ID if it would be possible ti communicate over it

**Comment by defnax** [comment]
> Hello,
> i*ve tried to install the apk-s linked in this thread to try testing the rs-mobile-app:
> Installed service apk and the mobile apk.
> Started service and than the rs-mobile:OK
> On trying to create a profile, the creation process was never ending,
> so the test stoped before we could try to connect two mobiles via rs-mobile.
> 
> So what was wrong or is there some specifics actual to be aware of to be able to create a profile?
> 
> I've an RS-TOR-ID if it would be possible to communicate over it.
> 
> Next days i will try to build the RS-Mobile by myself and try to get into the code.
> Maybe i will reach a point to support in coding it.

i has the same issues i doesnt have yet a android need to buy next weeks,  im mostly a iphone user,
on profile creation not ending like endless loop, when shut down retroshare and restart the profile generated and i can select to login.

same issue on login its very slow, i tested on blluestacks since few days.
when you are on retroshare we can chat there not sure about avinash, he isnt often online on retroshare.

**Comment by obrasero** [comment]
Hmm,(we use android)
to try to stop the App and restart it we also tried as we first tried the RS-andoid from f-droid.
This App did not end its intsall-process so we just stoped it and checked if it is there anyway; and it was.
Caused by this "experience" ;) we tried this also with the not ending profile creation on our android, but after restart it again needed a profile ti generate.

**Comment by defnax** [comment]
the service apk is very outdated from last year, i dont know but on bluestacks emultator it created, after i shutdown the retroshare-mobile
You are on retroshare? there is a dev chat better then here, avinash developing it alone im only testing what works and what not

**Comment by obrasero** [comment]
> You are on retroshare?

Yes, but with a TOR-Only RS.

> there is a dev chat better then here

How o get on it?
Until now, i'm also not a very experienced RS-User.
I use mostly dircet chat an d own created chatroom as well as mail-system.

**Comment by defnax** [comment]
> to try to stop the App and restart it we also tried as we first tried the RS-andoid from f-droid.

i dont know if f-droid is compatible with retroshare-mobile.
only working is the service apk from b1rd from last year with retroshare-mobile apk.

**Comment by defnax** [comment]
> > You are on retroshare?
> 
> Yes, but with a TOR-Only RS.
> 
> > there is a dev chat better then here
> 
> How o get on it?
> Until now, i'm also not a very experienced RS-User.
> I use mostly dircet chat an d own created chatroom as well as mail-system.

im not running tor rs, you are in dev test network?

**Comment by obrasero** [comment]
Yes, we tried first rs-forandroid from f-droid:
It was pefectly installable (but the not ending install-process) and we were able to successfully create a profile as well as to add friends.
But besides menus and there was not was to try to chat wit a contact.
So i thought it may be better to try the rs-mobile with the result posted above.

**Comment by obrasero** [comment]
> im not running tor rs, 

I also could create a non-tor RS-Profile it sutes better.

RS_TOR ist just the easiest and most robust way to use RS as it allways finds in  short the fare away frinds :)


> you are in dev test network

No, is this an RS-Network?

**Comment by defnax** [comment]
Yes im surprised that you are tested f-droid, that was only a protype some years ago(outdated), 
normaly that is not compatible with retroshare-mobile.

send me your cert via email ( no tor)

**Comment by obrasero** [comment]
If i read in this thread, that you are allready trying to deliver pictures by mobile-rs i thought it should allready satisfy the basi needs to me to be able to textual chat over:
Just only the textual chat would allready enogh to us to find it usable on a mobile. ;)

**Comment by obrasero** [comment]
> Yes im surprised that you are tested f-droid, that was only a protype some years ago(outdated),

Yes 3 Years old.
But its was otical an by menu allready looking an acting successfull for basic needs, but sorroly it was only optical witout realy chat avail :))

**Comment by defnax** [comment]
> > Yes im surprised that you are tested f-droid, that was only a protype some years ago(outdated),
> 
> Yes 3 Years old.
> But its was otical an by menu allready looking an acting successfull for basic needs, but sorroly it was only optical witout realy chat avail :))

when done send me your new rs profile key to my email

**Comment by obrasero** [comment]
key is running quickly bit by bit to your email-addr....

**Comment by defnax** [comment]
> key is running quickly bit by bit to your email-addr....

seems you has no dht ruuning?

> key is running quickly bit by bit to your email-addr....

send you are email reply, you has maybe no dht enabled?

**Comment by Kumaravinash9** [comment]
> > Hello,
> > i*ve tried to install the apk-s linked in this thread to try testing the rs-mobile-app:
> > Installed service apk and the mobile apk.
> > Started service and than the rs-mobile:OK
> > On trying to create a profile, the creation process was never ending,
> > so the test stoped before we could try to connect two mobiles via rs-mobile.
> > So what was wrong or is there some specifics actual to be aware of to be able to create a profile?
> > I've an RS-TOR-ID if it would be possible to communicate over it.
> > Next days i will try to build the RS-Mobile by myself and try to get into the code.
> > Maybe i will reach a point to support in coding it.
> 
> hi, i has the same issues i doesnt have yet a android need to buy next weeks, im mostly a iphone user,
> on profile creation not ending like endless loop, when shut down retroshare and restart the profile generated and i can select to login.
> 
> issues on login its very slow, i tested on bluestacks since few days.
> when you are on retroshare we can chat there not sure about avinash, he isnt often online on retroshare.

Hi @obrasero @defnax 
Actually retroshare service taking long time to process the account creation that's why it taking long time.

**Comment by Kumaravinash9** [comment]
I already inform this issue to @csoler

**Comment by obrasero** [comment]
> Actually retroshare service taking long time to process the account creation

You mean it is an recursively enumerable process, so it should end at some time successfully?

We waited realy a long time.
How long we need to wait, than i try it again.

But another question:
I play with the idea to help you in coding it.
But i think i need advice how to setup a successfull develop and debug environment for rs-mobile.
Would you help me o it?

**Comment by Kumaravinash9** [comment]
> > Actually retroshare service taking long time to process the account creation
> 
> You mean it is an recursively enumerable process, so it should end at some time successfully?
> 
> We waited realy a long time.
> How long we need to wait, than i try it again.
> 
> But another question:
> I play with the idea to help you in coding it.
> But i think i need advice how to setup a successfull develop and debug environment for rs-mobile.
> Would you help me o it?

Yes.  would be great if we will together.

**Comment by obrasero** [comment]
So, is it possible to chat with you over RS?
it would be easier nd i would like it more instead of the need to query-spam the gidhub on it.

**Comment by Kumaravinash9** [comment]
> > Actually retroshare service taking long time to process the account creation
> 
> You mean it is an recursively enumerable process, so it should end at some time successfully?
> 
> We waited realy a long time.
> How long we need to wait, than i try it again.
> 
> But another question:
> I play with the idea to help you in coding it.
> But i think i need advice how to setup a successfull develop and debug environment for rs-mobile.
> Would you help me o it?

Actually retroshare mobile send the http request to the retroshare-service. Once retroshare service return you the response then after circular indicator will stop and take you the identity_creating page

**Comment by Kumaravinash9** [comment]
> So, is it possible to chat with you over RS?
> it would be easier nd i would like it more instead of the need to query-spam the gidhub on it.

okk, Actually these days i am not much avaible on retroshare but sent you  invite the request

**Comment by obrasero** [comment]
> Once retroshare service return you the response then

Yes, but how long i need to wait on it to get an idea it realy done?

**Comment by obrasero** [comment]
> okk, Actually these days i am not much avaible on retroshare but sent you invite the request

Would be perfect if it's a invite for an RS-TOR-Only caus ethats normaly the only way i use RS.
To use RS without to i need to sit at home in front of my PC.

RS-OverTOR is reachable at home in company, just anywher by easy

**Comment by Kumaravinash9** [comment]
> > Once retroshare service return you the response then
> 
> Yes, but how long i need to wait on it to get an idea it realy done?

* For now please install flutter in your desktop 
* After sucessfully installing flutter , we will clone the repo 
* do flutter pub get
* Flutter run

**Comment by obrasero** [comment]
I should have written:
My Environment is Windos.

**Comment by Kumaravinash9** [comment]
> I should have written:
> My Environment is Windos.

great i also use windows. So, most probably it will work for you

**Comment by Kumaravinash9** [comment]
> look the image doesnt displayed on desktop
> not sure if mobile to mobile will be displayed right?
> image

Talking about i sent base64 string of image  to retroshare-service for sending images. I talked about this approach to the @csoler

**Comment by obrasero** [comment]
> There is one thing always keep your mind that you should not forget to install and start retroshare service.

The one delivered in actual RS-package or any special one?

**Comment by Kumaravinash9** [comment]
Two dependencies are :
*https://gitlab.com/Kumaravinash9/retroshare-dart-see
* https://gitlab.com/Kumaravinash9/openapi-dart-retroshare-api-wrapper
you can get Retroshare services  apk from this link : https://gitlab.com/Kumaravinash9/retroshare-android-apks

**Comment by obrasero** [comment]
fluuter doctor sais to have run
pup get.

is that enough?

**Comment by Kumaravinash9** [comment]
> fluuter doctor sais to have run
> pup get.
> 
> is that enough?

run this `flutter pub get`

**Comment by obrasero** [comment]
flutter doctor sais:

"unable to locate undroid-sdk"
So it seems to need more?
==> id doenload androidstuio and install it...

**Comment by Kumaravinash9** [comment]
> flutter doctor sais:
> 
> "unable to locate undroid-sdk"
> So it seems to need more?
> ==> id doenload androidstuio and install it...

You need to download android sdk

**Comment by obrasero** [comment]
doctor  lamments also to have no chrome.exe

**Comment by Kumaravinash9** [comment]
> doctor lamments also to have no chrome.exe

don't thing about it

**Comment by obrasero** [comment]
> Two dependencies are :
> *https://gitlab.com/Kumaravinash9/retroshare-dart-see
> *https://gitlab.com/Kumaravinash9/openapi-dart-retroshare-api-wrapper
> you can get Retroshare services apk from this link : https://gitlab.com/Kumaravinash9/retroshare-android-apks

OK:
- Flutter installed
- andorid studio installed and this did nstall sdk
- above git projects cloned 
- this service apk i allready had downloaded as wrote above it installed it on an android mobile

- pub get: delivers NO PUSPEC.yaml

**Comment by Kumaravinash9** [comment]
> > Two dependencies are :
> > *https://gitlab.com/Kumaravinash9/retroshare-dart-see
> > *https://gitlab.com/Kumaravinash9/openapi-dart-retroshare-api-wrapper
> > you can get Retroshare services apk from this link : https://gitlab.com/Kumaravinash9/retroshare-android-apks
> 
> OK:
> 
> * Flutter installed
> * andorid studio installed and this did nstall sdk
> * above git projects cloned
> * this service apk i allready had downloaded as wrote above it installed it on an android mobile
> * pub get: delivers NO PUSPEC.yaml
> 
> So, whats the problem of pub get? What i'm missing?

go to root dictory of retroshare mobile and do `flutter pub get`

**Comment by obrasero** [comment]
Ahh.. its to do in the project
now it runs ....... please wait, please wait ;)

**Comment by obrasero** [comment]
flutter run lamments to find no supported device

**Comment by Kumaravinash9** [comment]
> flutter run lamments to find no supported device

do one more thing,you need to add you realk device through usb and start developer mode in your  connected phone

**Comment by Kumaravinash9** [comment]
Follow this : https://www.youtube.com/watch?v=tmzoeyPn9vw

**Comment by obrasero** [comment]
no emulation avail so one does not need to conect real mobile?

**Comment by Kumaravinash9** [comment]
> no emulation avail so one does not need to conect real mobile?

You can use emulator but i has one problem you also nedd to download retroshare service in it

**Comment by obrasero** [comment]
ok, phone connected by usb and developermode activated, but run still says no supported device
need i to start the service on it?

**Comment by obrasero** [comment]
or need i to select a special mode for usb like file transfer, ptp,....?

**Comment by Kumaravinash9** [comment]
Do flutter devices it will show you that your phone is connected or not

**Comment by obrasero** [comment]
it say on econnected: edge

**Comment by Kumaravinash9** [comment]
It's means your phone is not connected with the device

**Comment by obrasero** [comment]
yes i know, but to know that it means this does not tell me what to do, that the phone gets connected....
phone is in develop mode
phone is with usb at the laptop....
why does flutter not find it?

**Comment by Kumaravinash9** [comment]
Go to the developer mode  and select USB connectivity

**Comment by obrasero** [comment]
well, there is no usb connectivity entry:
- usb debugging
- usb standard usb configuration
- usb audiorouting..
i assume i should somthing chane in
usb-standard config?

**Comment by Kumaravinash9** [comment]
USB debugging

**Comment by obrasero** [comment]
ok activated usb debugging
flutter devices still only lists edge.

**Comment by Kumaravinash9** [comment]
> ok activated usb debugging
> flutter devices still only lists edge.
Donot know why this is not working. Then i will help you to setup through emulator

**Comment by obrasero** [comment]
OK.
I know opened the rs-mobile project within android studio with flutter extension installed...
is actual saying it buidls....

**Comment by csoler** [comment]
@obrasero: if you want to connect to the dev Tor node, send your rs ID, and we'll send you the dev Tor node ID to connect to. From there you can easily access the dev forum and chats.

**Comment by obrasero** [comment]
send

**Comment by obrasero** [comment]
@Kumaravinash9:
Ok, removed all experimets and did all step by step again.
Result:
Andorid-Studio: OK
Flutter: doctor laments no illenesses
Flutter devices now gives me 3 :)
- a emulated one i created with AS
- my physical one
- and the useless edge from yester day.
- compiled in AS-Flutter the RS-Mobile successfull

But now:
How to tell the Project o run which of the devises to use and
how to autorize them which is lamented by flutter devises?

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9:
> Ok, removed all experimets and did all step by step again.
> Result:
> Andorid-Studio: OK
> Flutter: doctor laments no illenesses
> Flutter devices now gives me 3 :)
> 
> * a emulated one i created with AS
> * my physical one
> * and the useless edge from yester day.
> * compiled in AS-Flutter the RS-Mobile successfull
> 
> But now:
> How to tell the Project o run which of the devises to use and
> how to autorize them which is lamented by flutter devises?

Use Physical one and do flutter run

**Comment by obrasero** [comment]
> do flutter run

means call flutter run in console?

and that was one of the questions:
How to tell that it should use the physical one?

**Comment by obrasero** [comment]
Need i to flutter attach to assign a device?

**Comment by Kumaravinash9** [comment]
> > do flutter run
> 
> means call flutter run in console?
> 
> and that was one of the questions:
> How to tell that it should use the physical one?
do flutter run in terminal.

**Comment by obrasero** [comment]
> by flutter devices
> 1 connected device:
> Edge (web) • edge • web-javascript • Microsoft Edge 90.0.818.56
> • Device 123456789 is not authorized.
> You might need to check your device for an authorization dialog.

So how i get this phsical dev conneted/authorized

**Comment by Kumaravinash9** [comment]
On your device, go to Developer options-->Revoke USB Debugging and Disconnect your device. After reconnecting, you will get a RSA Fingerprint verification window, click on accept. Done..

**Comment by Kumaravinash9** [comment]
If that doesn't work then use this 
https://stackoverflow.com/questions/26079838/android-studio-adb-error-device-unauthorized-please-check-the-confirmat

**Comment by obrasero** [comment]
first seemed to work...
This fingerprint dialog i did allready accept.

So actual dont understand why it did not work.
But OK.
next steps to try...

**Comment by obrasero** [comment]
I see 2 RS apps in mobile.
I think one is ther service ond the other the ui, right?

**Comment by Kumaravinash9** [comment]
> I see 2 RS apps in mobile.
> I think one is ther service ond the other the ui, right?

Yes.

**Comment by Kumaravinash9** [comment]
@cyril , can you please merge this PR

**Comment by obrasero** [comment]
@Kumaravinash9 
it would be easier and less github spamming if we could write within RetroShare.
Still awaiting your Conection/invite.

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9
> it would be easier and less github spamming if we could write within RetroShare.
> Still awaiting your Conection/invite.

thanks @obrasero

**Comment by obrasero** [comment]
@@Kumaravinash9
Found you in the person-list and just send a distand invite to you.

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9
> Found you in the person-list and just send a distand invite to you.

Hello @obrasero, Now everything is working or not

**Comment by obrasero** [comment]
Did you receive m rs-invite?
are you online in RS?
---

yes it works basicaly, meaning:
- OK: futter run did install service and GUI on mobile
- OK: starting service on mobile
- OK: starting GUI
- OK: starting account creation
- FAIL: but after at least 0 min it is still in creation progress

**Comment by obrasero** [comment]
it is still in account creation processing.
Is there a way to braek this on the mobile or have i to stop flutter run?

**Comment by obrasero** [comment]
Yep,
succsessfull switched to talking via RS itself instead of spamming here ;)

**Pull request merged**
