### PR TITLE
fix identity profile pic

### PR DESCRIPTION
**Pull request by Kumaravinash9**

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
@cyril, Please check this out. It is working in your phone or not

**Comment by defnax** [comment]
@Kumaravinash9 
Avatar pictures working on Chats or profile?
i saw on konrads video some work ,im not sure how it looks now
he maked 2019 a video
https://vimeo.com/338567162

**Comment by Kumaravinash9** [comment]
> @Kumaravinash9
> Avatar pictures working on Chats or profile?
> i saw on konrads video some work ,im not sure how it looks now
> he maked 2019 a video
> https://vimeo.com/338567162

It changed now. I will show the whole video of new Retroshare App.

**Comment by Kumaravinash9** [comment]
@cyril, Can you please merge this PR. Now, i am working on forum support.

**Comment by defnax** [comment]
> > @Kumaravinash9
> > Avatar pictures working on Chats or profile?
> > i saw on konrads video some work ,im not sure how it looks now
> > he maked 2019 a video
> > https://vimeo.com/338567162
> 
> It changed now. I will show the whole video of new Retroshare App.

big issue on profile pictures its not stored maybe the pictures are lost when is offline? on qt ui we have the same issue no feature implemented store and load last used avatar.
i speak about ssl profile pictures, or this will never come to mobile version?

you speak about the gxs identities avatars right?

**Comment by defnax** [comment]
when you making first mobile testing apk?

**Comment by Kumaravinash9** [comment]
> when you making first mobile testing apk?
 Can i create a Apk whenever we want . But i planned  to make it when I have completed all the tasks.

**Comment by csoler** [comment]
I think that making an apk as soon as possible would be a good thing: it will allow more users to test. Besides, the effort needed to make an apk has to be done only once (a new apk can be done by running the same scripts again  I suppose) and will be needed anyway before the end of the project.

**Comment by Kumaravinash9** [comment]
Added Image support using base64 Regex function and Flutter Html package  : 
https://pub.dev/packages/flutter_html/example
https://stackoverflow.com/questions/8571501/how-to-check-whether-a-string-is-base64-encoded-or-not

**Comment by Kumaravinash9** [comment]
@csoler  @defnax  Will share you apk soon.

**Pull request merged**
