### PR TITLE
Buildsystem: Windows: howto flutter/android studio

### PR DESCRIPTION
**Pull request by obrasero**
I did add a description on how to setup the project buildsystem with flutter/androidstudio on windows.
The setps should be so detailed that also a first starter is able to get working.

### CODE REVIEW

**Comment by obrasero** [comment]
What about or how should i document the special testcases i applied and there result.
Is it possible/ok to these as an issue?
I couldnt find a marker to mark an issue as successful or failing test,
but i could think about it to just follow a fix convention in the issue-title like:
test:OK:Testtitel or
test:FAILED:Testtitel.

I'm not familiar with github to know if there or within this project is allready any way to do it.

**Comment by Kumaravinash9** [comment]
Thanks @obrasero for the PR.

**Comment by Kumaravinash9** [comment]
Hii @obrasero. Sending you apk can you help me to test the apk

**Comment by obrasero** [comment]
@obrasero. 
Yes i could
How will you send it, over RS?

**Comment by Kumaravinash9** [comment]
> @obrasero.
> Yes i could
> How will you send it, over RS?

#29

**Comment by Kumaravinash9** [comment]
When you are testing please make a video of it

**Comment by defnax** [comment]
> Here is the new apk according to the new retroshare-service version :
> 
> * Retroshare mobile : https://drive.google.com/file/d/1_3LTBwK_PDZDksTIf5gBAio5CNWmpWma/view?usp=sharing
> * Retroshare service : https://github.com/RetroShare/retroshare-mobile/blob/69a6bda8a6d45dc53a1c6ad0bf1eddaf2ee6bc10/android/retroshare-service/RetroShare_Android_Service-alpha-arm.apk
> 
> @csoler @defnax @obrasero Please test this app. Let me know login/signup is working or not

i get now errors, this wasnt happen before

image

**Comment by Kumaravinash9** [comment]
> > Here is the new apk according to the new retroshare-service version :
> > 
> > * Retroshare mobile : https://drive.google.com/file/d/1_3LTBwK_PDZDksTIf5gBAio5CNWmpWma/view?usp=sharing
> > * Retroshare service : https://github.com/RetroShare/retroshare-mobile/blob/69a6bda8a6d45dc53a1c6ad0bf1eddaf2ee6bc10/android/retroshare-service/RetroShare_Android_Service-alpha-arm.apk
> > 
> > @csoler @defnax @obrasero Please test this app. Let me know login/signup is working or not
> 
> i get now errors, this wasnt happen before
> 
> image

Did you insert the wrong passwrd I think

**Comment by defnax** [comment]
no wrong password
https://drive.google.com/file/d/1V6j4B2IDuUA4haBE33mBXHhqgam686sq/view?usp=sharing

**Comment by obrasero** [comment]
in case of wrong pwd dialog says: wrong password.
in case service down on login 
- sometimes a dialog telling the service is down
- sometimes just can't connect; the first is better as it tells what the problem ist, while this sugest the inet is not avail

it is possible to loose login state also service is not down.

it is possible rs is not reactive, wait,close app? also service is active, after a while the service may have gone, but rs-mobile never comes out of this wait, close app querying state as long as one types wait, regardless of restarting the service.

**Comment by Kumaravinash9** [comment]
> no wrong password, i only updated to you latest apk
> https://drive.google.com/file/d/1V6j4B2IDuUA4haBE33mBXHhqgam686sq/view?usp=sharing

Once you look at the codebase, Auth validation comes when retroshare service return res ==3 means your password is wrong.

**Comment by defnax** [comment]
> > no wrong password, i only updated to you latest apk
> > https://drive.google.com/file/d/1V6j4B2IDuUA4haBE33mBXHhqgam686sq/view?usp=sharing
> 
> Once you look at the codebase, Auth validation comes when retroshare service return res ==3 means your password is wrong.

possible after update the service i lost all passwords?
i deleted the service, and reinstalled, but i lost my test profiles, now cant create more a new profile.
i dont know maybe i need go back to older version to able to create a profile, not sure normaly profiel creation must work without issuse?

**Comment by Kumaravinash9** [comment]
> > > no wrong password, i only updated to you latest apk
> > > https://drive.google.com/file/d/1V6j4B2IDuUA4haBE33mBXHhqgam686sq/view?usp=sharing
> > 
> > 
> > Once you look at the codebase, Auth validation comes when retroshare service return res ==3 means your password is wrong.
> 
> possible after update the service i lost all passwords?
> i deleted the service, and reinstalled, but i lost my test profiles, now cant create more a new profile.
> i dont know maybe i need go back to older version to able to create a profile, not sure normaly profiel creation must work without issues?

Try to create a new profile with this version of retroshare

**Comment by defnax** [comment]
> > > > no wrong password, i only updated to you latest apk
> > > > https://drive.google.com/file/d/1V6j4B2IDuUA4haBE33mBXHhqgam686sq/view?usp=sharing
> > > 
> > > 
> > > Once you look at the codebase, Auth validation comes when retroshare service return res ==3 means your password is wrong.
> > 
> > 
> > possible after update the service i lost all passwords?
> > i deleted the service, and reinstalled, but i lost my test profiles, now cant create more a new profile.
> > i dont know maybe i need go back to older version to able to create a profile, not sure normaly profiel creation must work without issues?
> 
> Try to create a new profile with this new version of retroshare-service

no luck now, cant create profile more

**Comment by defnax** [comment]
can you make a new howto? it will be useful for new helpers

**Comment by Kumaravinash9** [comment]
> can you make a new howto? it will be useful for new helpers

I found the reason why this is happening. Will solve this problem  by this wednesday

**Comment by obrasero** [comment]
I unindendly closed it seesm by updating the howto.
As I dint know how to reopen it in github i just created a new as #35.

**Comment by defnax** [comment]
i did mostly all stuff from your howto installed last week, but the howto can be easier but thank fot that work .
only i did not the usb debug mode and tracing stuff, curl adb things...

**Pull request closed without merging**
