### PR TITLE
added short invite && Parse short invite feature

### PR DESCRIPTION
**Pull request by Kumaravinash9**
Fix : #6 
Fix : #8 
<table>
<tr>
<th> QR Scanner Screen</th>
<th> Add Friend Screen </th>
<th> About Screen </th>
</tr>
<tr>
  <td> </td>
  <td> </td>
  <td> </td>
</tr>
<tr>
<th> Create Identity  Screen</th>
<th> Change Identity Screen</th>
<th> Update Identity Screen </th>
</tr>
<tr>
  <td> </td>
  <td> </td>
  <td> </td>
</tr>
<tr>
<th> Identity Info Screen</th>
<th> Emoji Support I  </th>
<th> Emoji Support II </th>

</tr>
<tr>
<td> </td>
<td> </td>
 <td> </td>

</tr>
</table>

### CODE REVIEW

**Comment by Kumaravinash9** [comment]
please merge this PR @csoler

**Comment by Kumaravinash9** [comment]
Preview:
WhatsApp Image 2021-07-06 at 02 12 52

**Comment by defnax** [comment]
where is the short invite place or field?

**Comment by Kumaravinash9** [comment]
> where is the short invite place or field?

This QR Code contains the short invite data whenever a person scan this QR  he/she will automatically get the short invite.

**Comment by Kumaravinash9** [comment]
Hii @csoler, I have added the changes `createAccountV2` in the branch : https://github.com/Kumaravinash9/retroshare-mobile/tree/test
But i didnot update the retroshare services ,it's working  or not but most probably it should work. Please check it once

**Comment by csoler** [comment]
could you make a pull request to retroshare-mobile plz? It's easier for testing. I wont merge it. thx!

**Comment by Kumaravinash9** [comment]
> could you make a pull request to retroshare-mobile plz? It's easier for testing. I wont merge it. thx!
done.

**Comment by Kumaravinash9** [comment]
Preview Link : https://drive.google.com/file/d/1d2bKhm_TKmE_7V3zQPR2_AgFu1stXRdd/view?usp=sharing

**Comment by Kumaravinash9** [comment]
@csoler Please merge this PR.

**Comment by defnax** [comment]
> Preview Link : https://drive.google.com/file/d/1d2bKhm_TKmE_7V3zQPR2_AgFu1stXRdd/view?usp=sharing
> @csoler @defnax

looks nice thx

**Comment by csoler** [comment]
Is there a way to indicate that this short/long invite choice is for the sake of backward compatibility?
I mean, the long invite is only for people who need to connect to computers running a retroshare version < 0.6.6.
Users of your application will only need short invite since they all run the 0.6.6 core. 
So my suggestion is that you put some text next to the button "Retroshare 0.6.5 format" and always default to short invite.

**Comment by Kumaravinash9** [comment]
@csoler  Added info text and make default to short invite

**Comment by csoler** [comment]
Great! When you have the opportunity, the text should be 0.6.6 instead of 0.6. I'll merge it anyway. Just make that change when you want.

**Pull request merged**
